version: '3.8'

services:
  
  api:
    image: carbon390/politician-api:latest
    container_name: politician-api
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - X390-net
  
  frontend:
    image: carbon390/politician-frontend:latest
    container_name: politician-frontend
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - X390-net
    environment:
      
      
      - API_URL=http://api:8000/predict
    restart: unless-stopped

networks:
  X390-net:
    driver: bridge
