services:
  api-b0:
    image: carbon390/politician-api:latest
    container_name: politician-api-b0
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - X390-net

  api-b4:
    image: f230706/politician-classifier:v1
    container_name: politician-api-b4
    ports:
      - "8001:8000"
    restart: unless-stopped
    networks:
      - X390-net
  
  frontend:
    image: carbon390/politician-frontend:latest
    container_name: politician-frontend
    ports:
      - "8501:8501"
    depends_on:
      - api-b0
      - api-b4
    networks:
      - X390-net
    environment:
      - API_URL_B0=http://api-b0:8000/predict
      - API_URL_B4=http://api-b4:8000/predict
    restart: unless-stopped

networks:
  X390-net:
    driver: bridge
